---
language: python

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible

script:
  - ansible-galaxy init --role-skeleton=ansible-role-skeleton test_role

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
#  slack:
#    secure: "# out of `travis encrypt cjsteel:TOKEN-FROM-SLACK`"
#  email: false
